version: "3.8"

services:
  spring-app:
    build: .
    container_name: spring-boot-app
    ports:
      - "8084:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: unless-stopped
